### ISSUE TITLE
Publish DO failed with Authentication error

### ISSUE THREAD

**Issue by codehz** [cloudflare/wildebeest#146]
log
```
$ Running: wrangler publish --config do/wrangler.toml
 ⛅️ wrangler 2.8.0 
-------------------
✘ [ERROR] ParseError: A request to the Cloudflare API (/accounts/***/workers/services/wildebeest-do) failed.

      at throwFetchError (/usr/local/lib/node_modules/wrangler/wrangler-dist/cli.js:1[23](https://github.com/codehz/wildebeest/actions/runs/3972551377/jobs/6810556763#step:19:24)033:17)
      at fetchResult (/usr/local/lib/node_modules/wrangler/wrangler-dist/cli.js:123002:5)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async publish (/usr/local/lib/node_modules/wrangler/wrangler-dist/cli.js:126733:31)
      at async Object.publishHandler [as handler] (/usr/local/lib/node_modules/wrangler/wrangler-dist/cli.js:141579:3) {
    text: 'A request to the Cloudflare API (/accounts/***/workers/services/wildebeest-do) failed.',
    notes: [ { text: 'Authentication error [code: 10000]' } ],
    location: undefined,
    kind: 'error',
    code: 10000
  }



✘ [ERROR] A request to the Cloudflare API (/accounts/***/workers/scripts) failed.

  Authentication error [code: 10000]
  
  If you think this is a bug, please open an issue at: https://github.com/cloudflare/wrangler2/issues/new/choose
```
note: I use the generated token from `deploy to workers` button

**Comment by codehz** [comment]
It seems that I accidentally changed the API key options
