### ISSUE TITLE
[ERROR] ParseError: A request to the Cloudflare API (/accounts/***/workers/services/wildebeest-do) failed.

### ISSUE THREAD

**Issue by fqx** [cloudflare/wildebeest#149]
I have tried many times, the deploy sequence always stop at _Publish DO_ ,error log is

```
2023-01-21T11:06:09.8455119Z ##[group]Run cloudflare/wrangler-action@2.0.0
2023-01-21T11:06:09.8455450Z with:
2023-01-21T11:06:09.8455917Z   apiToken: ***
2023-01-21T11:06:09.8456200Z   command: publish --config do/wrangler.toml
2023-01-21T11:06:09.8456438Z env:
2023-01-21T11:06:09.8457045Z   OWNER_LOWER: fqx
2023-01-21T11:06:09.8457376Z   TERRAFORM_CLI_PATH: /home/runner/work/_temp/7b8b039f-a90d-45ad-a827-8e431c948bb7
2023-01-21T11:06:09.8457729Z   d1_id: 899b40d7-89db-4f90-9a60-9891b3986b64
2023-01-21T11:06:09.8457984Z   auth_domain: null
2023-01-21T11:06:09.8458451Z   CLOUDFLARE_ACCOUNT_ID: ***
2023-01-21T11:06:09.8458669Z ##[endgroup]
2023-01-21T11:06:09.8467822Z ##[command]/usr/bin/docker run --name ea425b6b1a29d59fb54a33998bd4056c2ebbdb_504fcc --label ea425b --workdir /github/workspace --rm -e "OWNER_LOWER" -e "TERRAFORM_CLI_PATH" -e "d1_id" -e "auth_domain" -e "CLOUDFLARE_ACCOUNT_ID" -e "INPUT_APITOKEN" -e "INPUT_COMMAND" -e "INPUT_APIKEY" -e "INPUT_EMAIL" -e "INPUT_ACCOUNTID" -e "INPUT_ENVIRONMENT" -e "INPUT_WORKINGDIRECTORY" -e "INPUT_WRANGLERVERSION" -e "INPUT_SECRETS" -e "INPUT_PRECOMMANDS" -e "INPUT_POSTCOMMANDS" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/wildebeest/wildebeest":"/github/workspace" ea425b:6b1a29d59fb54a33998bd4056c2ebbdb
2023-01-21T11:06:12.5410203Z npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
2023-01-21T11:06:12.5755000Z npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
2023-01-21T11:06:13.0648739Z 
2023-01-21T11:06:13.0649740Z added 101 packages, and audited 102 packages in 2s
2023-01-21T11:06:13.0650045Z 
2023-01-21T11:06:13.0650283Z 11 packages are looking for funding
2023-01-21T11:06:13.0650680Z   run `npm fund` for details
2023-01-21T11:06:13.0664968Z 
2023-01-21T11:06:13.0665344Z found 0 vulnerabilities
2023-01-21T11:06:13.0840109Z Using API Token authentication
2023-01-21T11:06:13.0841692Z $ Running: wrangler publish --config do/wrangler.toml
2023-01-21T11:06:13.9215150Z  ⛅️ wrangler 2.8.0 
2023-01-21T11:06:13.9215766Z -------------------
2023-01-21T11:06:14.3697499Z [31m✘ [41;31m[[41;97mERROR[41;31m][0m [1mParseError: A request to the Cloudflare API (/accounts/***/workers/services/wildebeest-do) failed.[0m
2023-01-21T11:06:14.3698092Z 
2023-01-21T11:06:14.3698512Z       at throwFetchError (/usr/local/lib/node_modules/wrangler/wrangler-dist/cli.js:123033:17)
2023-01-21T11:06:14.3699148Z       at fetchResult (/usr/local/lib/node_modules/wrangler/wrangler-dist/cli.js:123002:5)
2023-01-21T11:06:14.3699821Z       at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-01-21T11:06:14.3700611Z       at async publish (/usr/local/lib/node_modules/wrangler/wrangler-dist/cli.js:126733:31)
2023-01-21T11:06:14.3701535Z       at async Object.publishHandler [as handler] (/usr/local/lib/node_modules/wrangler/wrangler-dist/cli.js:141579:3) {
2023-01-21T11:06:14.3703246Z     text: 'A request to the Cloudflare API (/accounts/***/workers/services/wildebeest-do) failed.',
2023-01-21T11:06:14.3703930Z     notes: [ { text: 'Authentication error [code: 10000]' } ],
2023-01-21T11:06:14.3704230Z     location: undefined,
2023-01-21T11:06:14.3704720Z     kind: 'error',
2023-01-21T11:06:14.3704992Z     code: 10000
2023-01-21T11:06:14.3705301Z   }
2023-01-21T11:06:14.3705634Z 
2023-01-21T11:06:14.3705643Z 
2023-01-21T11:06:14.5075204Z 
2023-01-21T11:06:14.5097442Z [31m✘ [41;31m[[41;97mERROR[41;31m][0m [1mA request to the Cloudflare API (/accounts/***/workers/scripts) failed.[0m
2023-01-21T11:06:14.5097986Z 
2023-01-21T11:06:14.5098638Z   Authentication error [code: 10000]
2023-01-21T11:06:14.5098935Z   
2023-01-21T11:06:14.5100024Z   If you think this is a bug, please open an issue at: [4mhttps://github.com/cloudflare/wrangler2/issues/new/choose[0m
2023-01-21T11:06:14.5100453Z 
2023-01-21T11:06:14.5100595Z 

```

cURL for the same token returns code 10000 but with success

```
{"result":{"id":"f516959e1fe94372fe4adfc55c752659","status":"active"},"success":true,"errors":[],"messages":[{"code":10000,"message":"This API Token is valid and active","type":null}]}
```

I changed worker's default subdomain in the first time deploying, otherwise all default setting.
Tried different browser, same error.

**Comment by bvwjr** [comment]
Same issue. I enabled the unbound paid workers plan.

**Comment by fqx** [comment]
@bvwjr Does the paid plan solve the issue?

**Comment by bvwjr** [comment]
No.  Signed up for paid plan, getting the same error.

**Comment by nodomain** [comment]
Same here, just wanted to give the project a try...

**Comment by The-F4m3** [comment]
Hey,
I had the same Issue and solved it this way:
1. Update the Permissions of your API Token (main error), I added All Permissions from the default _Edit Cloudflare Workers_ API Template
2. now I got the error `In order to use Durable Objects, you must agree to pricing at https://dash.cloudflare.com/***/workers/overview?enable-durable-objects [code: 10084]` Paste your AccountId and Open the URL should open a Modal to Accept the Payment etc. 
  **Note**: I don't know if an Paid plan is needed for this
3. rerun the Action

**Comment by pgvee** [comment]
Durable objects don't exist on the free worker tier. 
![HCtOd69U0J](https://user-images.githubusercontent.com/422644/214345383-c160f70c-0907-4dc2-992a-6ff33e92e1c0.png)

**Comment by nodomain** [comment]
So yes, you need the paid plan. Then you can enable durable objects using the provided URL from the error message and your account ID.

Regarding the token, since I misunderstood it first: OP added the scopes from the "Edit Cloudflare Workers" API Template to the already created Wildebeest token. I can confirm that it works then.

So let's update documentation ;-) 

Note: as a complete Cloudflare newbie, I was unable to correctly configure the API scopes in the Deploy Button parameters. Perhaps somebody can add this.

**Comment by number5** [comment]
I don't think using Cloudflare Workers Paid Plan and enabling Durable Objects like @The-F4m3 mentioned is enough to fix this issue.

My Github Action run or running it locally e.g. `CLOUDFLARE_ACCOUNT_ID=21xxx CLOUDFLARE_API_TOKEN=dGxxxx pnpm wrangler publish --config consumer/wrangler.toml` still got `Code 10000` error

I have filed a bug on Wrangler project cloudflare/wrangler2/issues/2611

I did finish the deployment by doing `wrangler login` then `wrangler publish` locally though

**Comment by The-F4m3** [comment]
@number5 you also need add new permissions to the API Token. I don't know which is missing. But **adding** all missing ones compared to the "Edit Cloudflare Workers API" Template to the existing Token solved the permission problem.

**Comment by xtuc** [comment]
The Authentication error should now be fixed. There was a typo in the API token generation.
