### ISSUE TITLE
Error when following

### ISSUE THREAD

**Issue by huslage** [cloudflare/wildebeest#256]
I have deployed whatever version is current when this is filed. I am getting 500 errors whenever I try to follow someone. Any ideas on why I'd be seeing the `signature key not found` error?

<details><summary>Log Output</summary>

```json
{
  "outcome": "ok",
  "scriptName": "pages-worker--847492-production",
  "exceptions": [],
  "logs": [
    {
      "message": [
        "-> POST https://social.meedan.com/api/v1/accounts/cloudflare@cloudflare.social/follow "
      ],
      "level": "log",
      "timestamp": 1676083538265
    },
    {
      "message": [
        "query",
        "https://cloudflare.social/.well-known/webfinger?resource=acct%3Acloudflare%40cloudflare.social"
      ],
      "level": "log",
      "timestamp": 1676083538532
    },
    {
      "message": [
        {
          "body": "{\"@context\":\"https://www.w3.org/ns/activitystreams\",\"type\":\"Follow\",\"actor\":\"https://social.meedan.com/ap/users/aaron\",\"object\":\"https://cloudflare.social/ap/users/cloudflare\"}"
        }
      ],
      "level": "log",
      "timestamp": 1676083539061
    },
    {
      "message": [
        "Error: delivery to https://cloudflare.social/ap/users/cloudflare/inbox returned 401: signature key not found\n    at deliverToActor (worker.mjs:968:11)\n    at async handleRequest (worker.mjs:1271:3)\n    at async Object.next (worker.mjs:14922:26)\n    at async Object.next (worker.mjs:14922:26)\n    at async errorHandling (worker.mjs:14057:12)\n    at async Object.next (worker.mjs:14922:26)\n    at async logger (worker.mjs:10811:15)\n    at async next (worker.mjs:14922:26)\n    at async Object.fetch (worker.mjs:14936:14)",
        null
      ],
      "level": "error",
      "timestamp": 1676083539234
    },
    {
      "message": [
        "<- 500 (https://social.meedan.com/ap/users/aaron)"
      ],
      "level": "log",
      "timestamp": 1676083539234
    }
  ],
  "eventTimestamp": 1676083538265,
  "event": {
    "request": {
      "url": "https://social.meedan.com/api/v1/accounts/cloudflare@cloudflare.social/follow",
      "method": "POST",
      "headers": {
        "accept": "application/json",
        "accept-encoding": "gzip",
        "accept-language": "en-US,en;q=0.9",
        "authorization": "REDACTED",
        "cf-connecting-ip": "REDACTED",
        "cf-connecting-o2o": "1",
        "cf-ipcountry": "US",
        "cf-ray": "7979bfe20c30e3ae",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "content-length": "0",
        "host": "social.meedan.com",
        "origin": "https://pinafore.social",
        "priority": "u=1",
        "sec-ch-ua": "\"Not_A Brand\";v=\"99\", \"Google Chrome\";v=\"109\", \"Chromium\";v=\"109\"",
        "sec-ch-ua-mobile": "?0",
        "sec-ch-ua-platform": "\"macOS\"",
        "sec-fetch-dest": "empty",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "cross-site",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
        "x-forwarded-for": "REDACTED",
        "x-forwarded-proto": "https",
        "x-real-ip": "REDACTED"
      },
      "cf": {
        "longitude": "-78.62930",
        "httpProtocol": "HTTP/3",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "NA",
        "asn": 7018,
        "clientAcceptEncoding": "gzip",
        "country": "US",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsVersion": "TLSv1.3",
        "city": "REDACTED",
        "timezone": "America/New_York",
        "requestPriority": "",
        "edgeRequestKeepAliveStatus": 1,
        "postalCode": "REDACTED",
        "colo": "ATL",
        "latitude": "REDACTED",
        "region": "REDACTED",
        "regionCode": "REDACTED",
        "asOrganization": "AT&T Internet",
        "metroCode": "560",
        "pagesHostName": "wildebeest-huslage.pages.dev"
      }
    },
    "response": {
      "status": 500
    }
  },
  "id": 23
}
```
</details>

**Comment by huslage** [comment]
Update. I re-deployed from scratch (cleaned all assets from workers and pages) and am able to follow. There were no errors in the deploy log from the first run, so I have no idea what caused this problem. Please re-open this ticket if you need more info to help with it.
