### ISSUE TITLE
Search shows internal errors

### ISSUE THREAD

**Issue by pisceskaze** [cloudflare/wildebeest#257]
I have recently deployed successfully but it seems that I haven't get some of these thing to work properly yet...

Here is a request from my tablets mobile app that I captured with screen splitting.

```json
{
  "outcome": "ok",
  "scriptName": "pages-worker--845909-production",
  "exceptions": [],
  "logs": [
    {
      "message": [
        "-> GET https://nganha.songngu.xyz/api/v2/search?q=%40&resolve=true "
      ],
      "level": "log",
      "timestamp": 1676130647552
    },
    {
      "message": [
        "Error: invalid handle: localPart: \n    at parseHandle (worker.mjs:102:11)\n    at handleRequest28 (worker.mjs:4914:17)\n    at onRequest37 (worker.mjs:4962:14)\n    at Object.next (worker.mjs:14922:32)\n    at main (worker.mjs:5662:22)\n    at async Object.next (worker.mjs:14922:26)\n    at async errorHandling (worker.mjs:14057:12)\n    at async Object.next (worker.mjs:14922:26)\n    at async logger (worker.mjs:10811:15)\n    at async next (worker.mjs:14922:26)",
        null
      ],
      "level": "error",
      "timestamp": 1676130648064
    },
    {
      "message": [
        "<- 500 (https://nganha.songngu.xyz/ap/users/admin)"
      ],
      "level": "log",
      "timestamp": 1676130648064
    }
  ],
  "eventTimestamp": 1676130647552,
  "event": {
    "request": {
      "url": "https://nganha.songngu.xyz/api/v2/search?q=%40&resolve=true",
      "method": "GET",
      "headers": {
        "accept-encoding": "gzip",
        "authorization": "REDACTED",
        "cf-connecting-ip": "2001:ee0:5279:67c0:f824:33fe:9680:565c",
        "cf-connecting-o2o": "1",
        "cf-ipcountry": "VN",
        "cf-ray": "797e3e031fd06c2a",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "host": "nganha.songngu.xyz",
        "user-agent": "MastodonAndroid/1.1.4",
        "x-forwarded-for": "2001:ee0:5279:67c0:f824:33fe:9680:565c",
        "x-forwarded-proto": "https",
        "x-real-ip": "2001:ee0:5279:67c0:f824:33fe:9680:565c"
      },
      "cf": {
        "longitude": "106.65810",
        "httpProtocol": "HTTP/2",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "AS",
        "asn": 45899,
        "clientAcceptEncoding": "gzip",
        "country": "VN",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsVersion": "TLSv1.3",
        "city": "Ho Chi Minh City",
        "timezone": "Asia/Ho_Chi_Minh",
        "colo": "SIN",
        "edgeRequestKeepAliveStatus": 1,
        "requestPriority": "weight=16;exclusive=0;group=0;group-weight=0",
        "latitude": "10.83260",
        "region": "Ho Chi Minh",
        "regionCode": "SG",
        "asOrganization": "VNPT",
        "pagesHostName": "wildebeest-pisceskaze.pages.dev"
      }
    },
    "response": {
      "status": 500
    }
  },
  "id": 22
}
```

**Comment by pisceskaze** [comment]
And this time is a log, with a hashtag included on the toot.
```json
{
  "outcome": "ok",
  "scriptName": "pages-worker--850054-production",
  "exceptions": [],
  "logs": [
    {
      "message": [
        "-> GET https://nganha.songngu.xyz/api/v2/search?q=%23Test&type=hashtags "
      ],
      "level": "log",
      "timestamp": 1676181779607
    },
    {
      "message": [
        "Error: invalid handle: localPart: #Test\n    at parseHandle (worker.mjs:102:11)\n    at handleRequest28 (worker.mjs:4914:17)\n    at onRequest37 (worker.mjs:4962:14)\n    at Object.next (worker.mjs:14922:32)\n    at main (worker.mjs:5662:22)\n    at async Object.next (worker.mjs:14922:26)\n    at async errorHandling (worker.mjs:14057:12)\n    at async Object.next (worker.mjs:14922:26)\n    at async logger (worker.mjs:10811:15)\n    at async next (worker.mjs:14922:26)",
        null
      ],
      "level": "error",
      "timestamp": 1676181780002
    },
    {
      "message": [
        "<- 500 (https://nganha.songngu.xyz/ap/users/songngu)"
      ],
      "level": "log",
      "timestamp": 1676181780002
    }
  ],
  "eventTimestamp": 1676181779607,
  "event": {
    "request": {
      "url": "https://nganha.songngu.xyz/api/v2/search?q=%23Test&type=hashtags",
      "method": "GET",
      "headers": {
        "accept-encoding": "gzip",
        "authorization": "REDACTED",
        "cf-connecting-ip": "113.185.78.174",
        "cf-connecting-o2o": "1",
        "cf-ipcountry": "VN",
        "cf-ray": "79831e5a7cd9a054",
        "cf-visitor": "{\"scheme\":\"https\"}",
        "connection": "Keep-Alive",
        "host": "nganha.songngu.xyz",
        "user-agent": "MastodonAndroid/1.1.4",
        "x-forwarded-for": "113.185.78.174",
        "x-forwarded-proto": "https",
        "x-real-ip": "113.185.78.174"
      },
      "cf": {
        "longitude": "106.65810",
        "httpProtocol": "HTTP/2",
        "tlsCipher": "AEAD-AES128-GCM-SHA256",
        "continent": "AS",
        "asn": 45899,
        "clientAcceptEncoding": "gzip",
        "country": "VN",
        "tlsClientAuth": {
          "certIssuerDNLegacy": "",
          "certIssuerSKI": "",
          "certSubjectDNRFC2253": "",
          "certSubjectDNLegacy": "",
          "certFingerprintSHA256": "",
          "certNotBefore": "",
          "certSKI": "",
          "certSerial": "",
          "certIssuerDN": "",
          "certVerified": "NONE",
          "certNotAfter": "",
          "certSubjectDN": "",
          "certPresented": "0",
          "certRevoked": "0",
          "certIssuerSerial": "",
          "certIssuerDNRFC2253": "",
          "certFingerprintSHA1": ""
        },
        "tlsVersion": "TLSv1.3",
        "city": "Ho Chi Minh City",
        "timezone": "Asia/Ho_Chi_Minh",
        "colo": "SIN",
        "edgeRequestKeepAliveStatus": 1,
        "requestPriority": "weight=16;exclusive=0;group=0;group-weight=0",
        "latitude": "10.83260",
        "region": "Ho Chi Minh",
        "regionCode": "SG",
        "asOrganization": "VNPT",
        "pagesHostName": "wildebeest-pisceskaze.pages.dev"
      }
    },
    "response": {
      "status": 500
    }
  },
  "id": 17
}
```

**Comment by xtuc** [comment]
These shouldn't be errors, it's safe to ignore for now. They are failures to understand the search query.
