### ISSUE TITLE
Unsupported Update for Object type: Question

### ISSUE THREAD

**Issue by jahanson** [cloudflare/wildebeest#262]
Are polls supported in this release? They don't show in the timeline at all. A good account to test polls on is https://mastodon.social/@dungeons

Every time I receive an update for a poll I get a warning in the logs and it prevents anything from showing in the timeline:
(warn) unsupported Update for Object type: Question

The two errors I receive with this account are 
```
Unknown Event - Ok @ 2/11/2023, 8:51:08 AM
  (log) {"@context":["https://www.w3.org/ns/activitystreams","https://w3id.org/security/v1",{"manuallyApprovesFollowers":"as:manuallyApprovesFollowers","toot":"http://joinmastodon.org/ns#","featured":{"@id":"toot:featured","@type":"@id"},"featuredTags":{"@id":"toot:featuredTags","@type":"@id"},"alsoKnownAs":{"@id":"as:alsoKnownAs","@type":"@id"},"movedTo":{"@id":"as:movedTo","@type":"@id"},"schema":"http://schema.org#","PropertyValue":"schema:PropertyValue","value":"schema:value","discoverable":"toot:discoverable","Device":"toot:Device","Ed25519Signature":"toot:Ed25519Signature","Ed25519Key":"toot:Ed25519Key","Curve25519Key":"toot:Curve25519Key","EncryptedMessage":"toot:EncryptedMessage","publicKeyBase64":"toot:publicKeyBase64","deviceId":"toot:deviceId","claim":{"@type":"@id","@id":"toot:claim"},"fingerprintKey":{"@type":"@id","@id":"toot:fingerprintKey"},"identityKey":{"@type":"@id","@id":"toot:identityKey"},"devices":{"@type":"@id","@id":"toot:devices"},"messageFranking":"toot:messageFranking","messageType":"toot:messageType","cipherText":"toot:cipherText","suspended":"toot:suspended","focalPoint":{"@container":"@list","@id":"toot:focalPoint"}}],"id":"https://mastodon.social/users/dungeons#updates/1676127037","type":"Update","actor":"https://mastodon.social/users/dungeons","to":["https://www.w3.org/ns/activitystreams#Public"],"object":{"id":"https://mastodon.social/users/dungeons","type":"Service","following":"https://mastodon.social/users/dungeons/following","followers":"https://mastodon.social/users/dungeons/followers","inbox":"https://mastodon.social/users/dungeons/inbox","outbox":"https://mastodon.social/users/dungeons/outbox","featured":"https://mastodon.social/users/dungeons/collections/featured","featuredTags":"https://mastodon.social/users/dungeons/collections/tags","preferredUsername":"dungeons","name":"Dungeons","summary":"<p>⚔️ Ꭿﬡ𝘭ꭿﬡ, the Dragonborn Fighter<br />❤️❤️❤️❤️❤️
❤️❤️🖤🖤🖤 10/15<br />⭐ 2 (310) 🎲 1/2<br />🗡️ Lance [1d12+5, +7] 🛡️ Shield <br />🛡️ Ring Mail [16]<br />🪙 53<br />
Str 20 Dex 12 Con 12 Int 10 Wis 12 Cha 13</p><p>🗺️ 31 🕔 1 day, 05:01</p>","url":"https://mastodon.social/@dungeons","m
anuallyApprovesFollowers":false,"discoverable":true,"published":"2022-11-16T00:00:00Z","devices":"https://mastodon.social/users/dungeons/collections/devices","publicKey":{"id":"https://mastodon.social/users/dungeons#main-key","owner":"https://mastodon.social/users/dungeons","publicKeyPem":"-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsZSBM7kMyW6/Q7p5yxvp\nlcxybbOmT9GQtI0022UNl/PjQBqG8+Oi5PwUCwnSrkVLLPJ4aXQ2nQpnswJu/rdj\nanRyx2T1gziCLt4O6U6rJGIw045tqTbmdXMtwlhu+ECXQXk5rH2IgN6V29cbdU2Q\nSN1C33ZCqpbEBZQNakWfWhu8bNLyiIc46/mPE74LAk0T/+7CYvOFx0GkNrYJplma\n2oG9z82HQ2YdsFtNKwO1bqNxiGsMXS/TQjrBFuaja+DKIU+ytEaB9mfHX1ZmVFjI\nUkgxw5Yg2INR5jtVqFb3vHX6ZmysI2Upo06pzhSAKBJZ/0QGPBh5LgM2nTyvty94\nvwIDAQAB\n-----END PUBLIC KEY-----\n"},"tag":[],"attachment":[{"type":"PropertyValue","name":"Tips & Info","value":"<a href=\"https://dungeons.astrelion.com\" target=\"_blank\" rel=\"nofollow noopener noreferrer me\"><span class=\"invisible\">https://</span><span class=\"\">dungeons.astrelion.com</span><span class=\"invisible\"></span></a>"},{"type":"PropertyValue","name":"Author","value":"<span class=\"h-card\"><a href=\"https://mastodon.social/@astrelion\" class=\"u-url mention\">@<span>astrelion</span></a></span>"},{"type":"PropertyValue","name":"Source","value":"<a href=\"https://gitlab.com/ASTRELION/dungeons-bot\" target=\"_blank\" rel=\"nofollow noopener noreferrer me\"><span class=\"invisible\">https://</span><span class=\"ellipsis\">gitlab.com/ASTRELION/dungeons-</span><span class=\"invisible\">bot</span></a>"}],"endpoints":{"sharedInbox":"https://mastodon.social/inbox"},"icon":{"type":"Image","mediaType":"image/png","url":"https://files.mastodon.social/accounts/avatars/109/354/069/933/492/315/original/20001dae7df896ce.png"},"image":{"type":"Image","mediaType":"image/png","url":"https://files.mastodon.social/accounts/headers/109/354/069/933/492/315/original/f01d631da5b476fe.png"}},"signature":{"type":"RsaSignature2017","creator":"https://mastodon.social/users/dungeons#main-key","created":"2023-02-11T14:50:37Z","signatureValue":"TrFc+lqZGeRgOV8fIZcRSv2G8esQ5itehqgPETvE4FzFG6vDyGUpDXW2y2p3ZosT+KWmVhKHi1/NwZg7/g6CtDebvfAwneeaBBOaRum65v0PviMYQwxd41Z6uw25YreZpNB6MuwyR/sBAl1vcj+63j1r4NsziGdRei18JM74l9mqlDsiKFeneZiiS/Udnidsklr4+XFjet/PEE7v/vRTUt0QT1+lNON5JeLQI5X7Gnt62dpK6EZxS5FQ2/zm94Ru0t7Qmvh0lRvxEEtx6mpXvu26kcaACVw7rIGEno5cHYHN3zZI9RPu6wqTBRnT6ogvyc7uzm+m3rHd4lEm3gBWNQ=="}}
  (error) Error: object https://mastodon.social/users/dungeons does not exist
    at handle (d1-beta-facade.entry.js:4467:15)
    at async handleInboxMessage (d1-beta-facade.entry.js:4771:3)
    at async Object.queue (d1-beta-facade.entry.js:4803:13) null
```

```
Unknown Event - Ok @ 2/11/2023, 8:55:11 AM
 (log) {"@context":["https://www.w3.org/ns/activitystreams",{"ostatus":"http://ostatus.org#","atomUri":"ostatus:atomUri","inReplyToAtomUri":"ostatus:inReplyToAtomUri","conversation":"ostatus:conversation","sensitive":"as:sensitive","toot":"http://joinmastodon.org/ns#","votersCount":"toot:votersCount"}],"id":"https://mastodon.social/users/dungeons/statuses/109846543497026220#updates/1676126885","type":"Update","actor":"https://mastodon.social/users/dungeons","to":["https://www.w3.org/ns/activitystreams#Public"],"object":{"id":"https://mastodon.social/users/dungeons/statuses/109846543497026220","type":"Question","summary":null,"inReplyTo":"https://mastodon.social/users/dungeons/statuses/109846425442798354","published":"2023-02-11T14:20:36Z","url":"https://mastodon.social/@dungeons/109846543497026220","attributedTo":"https://mastodon.social/users/dungeons","to":["https://www.w3.org/ns/activitystreams#Public"],"cc":["https://mastodon.social/users/dungeons/followers"],"sensitive":false,"atomUri":"https://mastodon.social/users/dungeons/statuses/109846543497026220","inReplyToAtomUri":"https://mastodon.social/users/dungeons/statuses/109846425442798354","conversation":"tag:mastodon.social,2023-02-10:objectId=395106738:objectType=Conversation","content":"<p>You confronted the Owl!<br />---<br />🦁 Owl<br />❤️ 1/1<br />🛡️ 11 ☁️<br />❕0<br />✨ 10</p>","contentMap":{"en":"<p>You confronted the Owl!<br />---<br />🦁 Owl<br />❤
️ 1/1<br />🛡️ 11 ☁️<br />❕0<br />✨ 10</p>"},"endTime":"2023-02-11T14:50:36Z","closed":"2023-02-11T14:50:36Z","votersCount":27,"attachment":[],"tag":[],"repli
es":{"id":"https://mastodon.social/users/dungeons/statuses/109846543497026220/replies","type":"Collection","first":{"type":"CollectionPage","next":"https://mastodon.social/users/dungeons/statuses/109846543497026220/replies?min_id=109846661571196733&page=true","partOf":"https://mastodon.social/users/dungeons/statuses/109846543497026220/replies","items":["https://mastodon.social/users/dungeons/statuses/109846661571196733"]}},"oneOf":[{"type":"Note","name":"⚔️ Melee Attack, one-handed [1d12]","replies":{"type":"Collection","totalItems":14}},{"type":"Note","name":"🏹 Ranged Attack, improvised [1d4]","replies":{"type":"Collection","totalItems":9}},{"type":"Note","name":"👊 Melee Attack, unarmed [6]","replies":{"type":"Collection","totalItems":3}},{"type":"Note","name":"🏃 Run!","replies":{"type":"Collection","totalItems":1}}]},"signature":{"type":"RsaSignature2017","creator":"https://mastodon.social/users/dungeons#main-key","created":"2023-02-11T14:51:10Z","signatureValue":"mLUHFJQM0opEdYw5vQQ9QoxO3Ys3dnk7JId1WH+NflQKyLCaxuNWHRcLoaEgI5p1f3Uf8KPI+QraxdIqBaGreXqBqlMk04Y9Fv6uPLKENns4AYf2D5Iwa6mIDeV5Zp3Kczu1k4seSrVv5YhcA+eM2Wsk37mqsvnzp+LafFfluW2B7tItOJpsJppRByxY0dtwO5A2coA6J5fTXYmBp1LRvRx7NM7o8terEBkL1U/6BKqjbopKYmVsBd3t7sV3IZu8BRn/3+wfpe4ostVAeG9lpe6hmyO38NxWo5fcq0R0vCmWpwhRMe/7nRqd9ZOiebNTYqmxp8aQC+9hSvxaGlvFAA=="}}
  (warn) unsupported Update for Object type: Question
```

**Comment by xtuc** [comment]
Polls are currently not implemented.
